### ISSUE TITLE
Error handling should display the problematic record

### ISSUE THREAD

**Issue by johanneskoester** [vembrane/vembrane#156]
When anything goes wrong during filtering, it would be great to get an info about which record failed. This way, it would be more easily possible to find out what is wrong.

Moreover, if ANN is malformed I get the following error currently:
```
Traceback (most recent call last):
  File "/projects/koesterlab/neopredict-lung/analysis/wes/.snakemake/conda/1f4001459aeea256e7b7a72b00d7ca91_/lib/python3.10/site-packages/vembrane/representations.py", line 171, in __getitem__
    return self._data[item]
KeyError: 'SYMBOL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/projects/koesterlab/neopredict-lung/analysis/wes/.snakemake/conda/1f4001459aeea256e7b7a72b00d7ca91_/bin/vembrane", line 10, in <module>
    sys.exit(main())
  File "/projects/koesterlab/neopredict-lung/analysis/wes/.snakemake/conda/1f4001459aeea256e7b7a72b00d7ca91_/lib/python3.10/site-packages/vembrane/cli.py", line 23, in main
    filter.execute(args)
  File "/projects/koesterlab/neopredict-lung/analysis/wes/.snakemake/conda/1f4001459aeea256e7b7a72b00d7ca91_/lib/python3.10/site-packages/vembrane/modules/filter.py", line 345, in execute
    first_record = list(islice(records, 1))
  File "/projects/koesterlab/neopredict-lung/analysis/wes/.snakemake/conda/1f4001459aeea256e7b7a72b00d7ca91_/lib/python3.10/site-packages/vembrane/modules/filter.py", line 192, in filter_vcf
    record, keep = test_and_update_record(
  File "/projects/koesterlab/neopredict-lung/analysis/wes/.snakemake/conda/1f4001459aeea256e7b7a72b00d7ca91_/lib/python3.10/site-packages/vembrane/modules/filter.py", line 143, in test_and_update_record
    filtered_annotations = [
  File "/projects/koesterlab/neopredict-lung/analysis/wes/.snakemake/conda/1f4001459aeea256e7b7a72b00d7ca91_/lib/python3.10/site-packages/vembrane/modules/filter.py", line 144, in <listcomp>
    annotation for annotation in annotations if env.evaluate(annotation)
  File "/projects/koesterlab/neopredict-lung/analysis/wes/.snakemake/conda/1f4001459aeea256e7b7a72b00d7ca91_/lib/python3.10/site-packages/vembrane/representations.py", line 390, in evaluate
    return self._func()
  File "<string>", line 1, in <lambda>
  File "/projects/koesterlab/neopredict-lung/analysis/wes/.snakemake/conda/1f4001459aeea256e7b7a72b00d7ca91_/lib/python3.10/site-packages/vembrane/representations.py", line 30, in __contains__
    value = self[item]
  File "/projects/koesterlab/neopredict-lung/analysis/wes/.snakemake/conda/1f4001459aeea256e7b7a72b00d7ca91_/lib/python3.10/site-packages/vembrane/representations.py", line 177, in __getitem__
    raw_value = self._annotation_data[ann_idx].strip()
IndexError: list index out of range
```

**Comment by tedil** [comment]
All error instances of `UnknownAnnotation`, `UnknownSample`, `UnknownFormatField` and `UnknownInfoField` (in vembrane/errors.py) keep track of the record index and the record itself and also print out a string representation of the record.
However, any *uncaught*/*unexpected* errors will not have that information.

The malformed ANN string could probably be checked for and a corresponding, more informative error message could be generated.

Generally, we could perhaps simply wrap the relevant parts in a catch all try-except and re-raise the error after printing out the record information. Is that what you mean?
